# Generated by Django 3.2.19 on 2023-06-05 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Name', max_length=1000)),
                ('comment', models.TextField(default='Body')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Name', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/postsImage')),
            ],
        ),
        migrations.CreateModel(
            name='Replyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Name', max_length=1000)),
                ('reply', models.TextField(default='Body')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('auhtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
                ('comments', models.ManyToManyField(blank=True, null=True, related_name='Comments', to='Posts.Comments')),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='images', to='Posts.Image')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='replyes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Replyes', to='Posts.Replyes'),
        ),
    ]
