# Generated by Django 3.2.19 on 2025-03-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='Body')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='Commentlikes', to='Users.Profile')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=255)),
                ('file', models.FileField(blank=True, upload_to='media/postsMedia')),
                ('hls_directory', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(default='Body')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='Replylikes', to='Users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('auhtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
                ('comments', models.ManyToManyField(blank=True, null=True, related_name='Comments', to='Posts.Comment')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='likes', to='Users.Profile')),
                ('media_files', models.ManyToManyField(blank=True, null=True, related_name='media', to='Posts.MediaFile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='replyes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Replyes', to='Posts.Reply'),
        ),
    ]
