# Generated by Django 3.2.19 on 2023-06-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Replyes',
            new_name='Reply',
        ),
    ]
