# Generated by Django 3.2.19 on 2023-06-05 19:40

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20230604_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/postsMedia', validators=[Posts.models.FileTypeValidator()])),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='media_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='media', to='Posts.MediaFile'),
        ),
    ]
