# Generated by Django 3.2.13 on 2023-06-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20230611_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='temp_files',
            new_name='chunks',
        ),
    ]
