# Generated by Django 3.2.19 on 2023-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_rename_temp_files_mediafile_chunks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='chunks',
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, upload_to='media/postsMedia'),
        ),
    ]
