# Generated by Django 3.2.19 on 2023-06-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20230612_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, upload_to='media/originals'),
        ),
    ]
