# Generated by Django 3.2.19 on 2023-07-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Posts', '0011_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Commentlikes', to='Users.Profile'),
        ),
    ]
