# Generated by Django 3.2.19 on 2023-07-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Posts', '0013_remove_reply_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Replylikes', to='Users.Profile'),
        ),
    ]
