# Generated by Django 3.2.19 on 2025-03-19 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=200)),
                ('firstname', models.CharField(default='firstname', max_length=200)),
                ('lastname', models.CharField(default='lastname', max_length=200)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_picture', models.ImageField(default='default_profile_picture.png', upload_to='profile_pictures/')),
                ('cover_image', models.ImageField(default='default_profile_picture.png', upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='following', to='Users.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
