# Generated by Django 3.2.19 on 2023-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='default_profile_picture.png', upload_to='profile_pictures/'),
        ),
    ]
